/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.erik.aula04;

import javax.swing.JOptionPane;

/**
 *
 * @author 08307
 */
public class JFTela extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public JFTela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtnome = new javax.swing.JTextField();
        btncontar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtpagamento = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtjuros = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtatraso = new javax.swing.JTextField();
        btncalcular = new javax.swing.JButton();
        lbtotal = new javax.swing.JLabel();
        btnint = new javax.swing.JButton();
        btnloop = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Digite o seu nome:");

        btncontar.setText("Contar letras");
        btncontar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncontarActionPerformed(evt);
            }
        });

        jLabel2.setText("Valor do pagamento");

        jLabel3.setText("Taxa de juros");

        txtjuros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjurosActionPerformed(evt);
            }
        });

        jLabel4.setText("Dias de atraso");

        btncalcular.setText("Calcular");
        btncalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalcularActionPerformed(evt);
            }
        });

        lbtotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbtotal.setText("Total a pagar: R$ 0,00");

        btnint.setText("Int..else");
        btnint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnintActionPerformed(evt);
            }
        });

        btnloop.setText("loop");
        btnloop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtatraso, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtjuros, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtpagamento, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnome))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btncontar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btncalcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnloop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbtotal, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncontar))
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncalcular))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtjuros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnint))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtatraso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnloop))
                .addGap(18, 18, 18)
                .addComponent(lbtotal)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncontarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncontarActionPerformed
        // TODO add your handling code here:
        String nome = txtnome.getText();
        int tamanho = nome.length();
        JOptionPane.showMessageDialog(null, "A palavra tem "+tamanho+" letras");
    }//GEN-LAST:event_btncontarActionPerformed

    private void txtjurosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjurosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjurosActionPerformed

    private void btncalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalcularActionPerformed
        // TODO add your handling code here:
        double valor = Double.valueOf(txtpagamento.getText());
        double taxa = Double.valueOf(txtjuros.getText());
        int atraso = Integer.valueOf(txtatraso.getText());
        
        double juros = taxa * valor * atraso;
        double montante = valor + juros;
        lbtotal.setText("Total a pagar R$: "+montante);
    }//GEN-LAST:event_btncalcularActionPerformed

    private void btnintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnintActionPerformed
        // TODO add your handling code here:
        int a = Integer.valueOf(txtpagamento.getText());
        int b = Integer.valueOf(txtjuros.getText());
        int c = Integer.valueOf(txtatraso.getText());
        String mensagem = "";
        
        if(a>b && a>c){
           mensagem = "A é o maior valor"; 
        }else if(b>a && b>c){
            mensagem = "B é o maior valor";
        }else if(c>a && c>b){
            mensagem = "C é o maior valor";
        }else{
            mensagem = "Resultado não esperado";
        }
        JOptionPane.showMessageDialog(null, mensagem);
        
    }//GEN-LAST:event_btnintActionPerformed

    private void btnloopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloopActionPerformed
        // TODO add your handling code here:
        for(int i=1; i<=5; i++);{
            JOptionPane.showMessageDialog(null, "vou repetir"+ i+" vezes");   
    }
        
    }//GEN-LAST:event_btnloopActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncalcular;
    private javax.swing.JButton btncontar;
    private javax.swing.JButton btnint;
    private javax.swing.JButton btnloop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbtotal;
    private javax.swing.JTextField txtatraso;
    private javax.swing.JTextField txtjuros;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txtpagamento;
    // End of variables declaration//GEN-END:variables
}
